<?php
// Start the session
session_start();

// Restrict access to non-admin priviledged users
if (!isset($_SESSION['login']) && !isset($_SESSION['role'])) {
    header("Location: ../index.php");
} else if (isset($_SESSION['role'])) {
    if ($_SESSION['role'] != "Admin" && $_SESSION['role'] != "Station Staff" && $_SESSION['role'] != "Railway Operator" && $_SESSION['role'] != "Cater Staff") {
        header("Location: ../index.php");
    }
}

// Include required classes
require_once '../vendor/autoload.php'; 
require_once '../classes/DbConnector.php';
require_once '../classes/Admin.php';
require_once '../classes/CaterStaff.php';
require_once '../classes/RailwayOperator.php';
require_once '../classes/StationStaff.php';

use classes\DbConnector;
use classes\Admin;
use classes\CaterStaff;
use classes\RailwayOperator;
use classes\StationStaff;

// Set time-zone to GMT +5.30
date_default_timezone_set('Asia/Kolkata');

// Get current date & time
$currentDateTime = date("Y-m-d H:i:s");

// Get username of the current looged in user
$username = $_SESSION['username'];

// Establish a connection with the database
$dbcon = new DbConnector;
$con = $dbcon->connect();

// Generate HTML content based on the user role
if ($_SESSION['role'] == "Admin") {
    $rs1 = Admin::getPassengers();
    $rs2 = Admin::getOtherUsers();
    $rs3 = Admin::getReviews();
    $rs4 = Admin::getChatBot();

    $rs1Count = count($rs1);
    $rs2Count = count($rs2);
    $rs3Count = Admin::getReviewCount();
    $rs4Count = Admin::getChatBotCount();

    // Generate HTML content for the report
    $html = "
    <html>
        <head>
            <style>
                table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
                }
            </style>
        </head>
        <body>
            <h1 align='center'>Statistical Report - Admin</h1>
            <h4>Generated by: $username</h4>
            <h4>Generated at: $currentDateTime</h4>
            <h3><u>Passengers</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Telephone</th>
                            <th>Email</th>
                            <th>NIC</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs1) > 0) {
                        for ($i = 0; $i < count($rs1); $i++) {
                            $row = $rs1[$i];
                            $index = $i + 1;
                            $rs1Username = $row['UserName'];
                            $rs1Fname = $row['First_Name'];
                            $rs1Lname = $row['Last_Name'];
                            $rs1Telephone = $row['Telephone'];
                            $rs1Email = $row['Email'];
                            $rs1NIC = $row['NIC'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs1Username</td>
                            <td>$rs1Fname</td>
                            <td>$rs1Lname</td>
                            <td>$rs1Telephone</td>
                            <td>$rs1Email</td>
                            <td>$rs1NIC</td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='7'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total passengers: $rs1Count</span>
            </div>
            <h3><u>Other Users</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Role</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs2) > 0) {
                        for ($i = 0; $i < count($rs2); $i++) {
                            $row = $rs2[$i];
                            $index = $i + 1;
                            $rs2Username = $row['UserName'];
                            $rs2Role = $row['Role'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs2Username</td>
                            <td>$rs2Role</td>
                        </tr>
                    ";
                        }
                    } else {
                    $html .= "
                        <tr>
                            <td colspan='3'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total other users: $rs2Count</span>
            </div>
            <h3><u>Reviews</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Rate</th>
                            <th>Title</th>
                            <th>Body</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs3) > 0) {
                        for ($i = 0; $i < count($rs3); $i++) {
                            $row = $rs3[$i];
                            $index = $i + 1;
                            $rs3Username = $row['UserName'];
                            $rs3Rate = $row['Rate'];
                            $rs3Title = $row['Title'];
                            $rs3Body = $row['Body'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs3Username</td>
                            <td>$rs3Rate</td>
                            <td>$rs3Title</td>
                            <td>$rs3Body</td>
                        </tr>
                            ";
                        }
                    } else {
                    $html .= "
                        <tr>
                            <td colspan='5'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total reviews: $rs3Count</span>
            </div>
            <h3><u>ChatBot</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Question</th>
                            <th>Reply</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs4) > 0) {
                        for ($i = 0; $i < count($rs4); $i++) {
                            $row = $rs4[$i];
                            $index = $i + 1;
                            $rs4Question = $row['Question'];
                            $rs4Reply = $row['Reply'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs4Question</td>
                            <td>$rs4Reply</td>
                        </tr>
                            ";
                        }
                    } else {
                    $html .= "
                        <tr>
                            <td colspan='3'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total reviews: $rs4Count</span>
            </div>
        </body>
    </html>
    ";
} else if ($_SESSION['role'] == "Station Staff") {
    $rs1 = StationStaff::getReservation();
    $rs2 = StationStaff::getStation();
    $rs3 = StationStaff::getNotice();

    $rs1Count = StationStaff::getReservationCount();
    $rs2Count = StationStaff::getStationCount();
    $rs3Count = StationStaff::getNoticeCount();
    $rs1Sum = StationStaff::getSum();

    // Generate HTML content for the report
    $html = "
    <html>
        <head>
            <style>
                table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
                }
            </style>
        </head>
        <body>
            <h1 align='center'>Statistical Report - Station Staff</h1>
            <h4>Generated by: $username</h4>
            <h4>Generated at: $currentDateTime</h4>
            <h3><u>Route</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Schedule ID</th>
                            <th>Class</th>
                            <th>Qty</th>
                            <th>Price</th>
                            <th>Res. Date</th>
                            <th>Exp. Date</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs1) > 0) {
                        for ($i = 0; $i < count($rs1); $i++) {
                            $row = $rs1[$i];

                            $query1 = "SELECT UserName FROM User WHERE User_Id = ?;";
                            $pstmt1 = $con->prepare($query1);
                            $pstmt1->bindValue(1, $row['User_Id']);
                            $pstmt1->execute();
                            $rs4 = $pstmt1->fetch(PDO::FETCH_BOTH);

                            $query2 = "SELECT Email FROM User_Details WHERE User_Id = ?;";
                            $pstmt2 = $con->prepare($query2);
                            $pstmt2->bindValue(1, $row['User_Id']);
                            $pstmt2->execute();
                            $rs5 = $pstmt2->fetch(PDO::FETCH_BOTH);

                            $index = $i + 1;
                            $rs1Username = $rs4[0];
                            $rs1Email = $rs5[0];
                            $rs1ScheduleId = $row['Schedule_Id'];
                            $rs1Class = $row['Class'];
                            $rs1Quantity = $row['Quantity'];
                            $rs1Price = $row['Price'];
                            $rs1ResDate = $row['Res_Date'];
                            $rs1ExpDate = $row['Exp_Date'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs1Username</td>
                            <td>$rs1Email</td>
                            <td>$rs1ScheduleId</td>
                            <td>$rs1Class</td>
                            <td>$rs1Quantity</td>
                            <td>$rs1Price</td>
                            <td>$rs1ResDate</td>
                            <td>$rs1ExpDate</td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='9'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total reservations: $rs1Count</span>
                <br>
                <span>Total income: $rs1Sum</span>
            </div>
            <h3><u>Station</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Station Name</th>
                        </tr>
                    </thead>
                    <tbody>";
                    $dbcon = new DbConnector;
                    $con = $dbcon->connect();
                    if (count($rs2) > 0) {
                        for ($i = 0; $i < count($rs2); $i++) {
                            $row = $rs2[$i];
                            $index = $i + 1;
                            $rs2StationName = $row['Station_Name'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs2StationName</td>
                        </tr>
                    ";
                        }
                    } else {
                    $html .= "
                        <tr>
                            <td colspan='2'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total stations: $rs2Count</span>
            </div>
            <h3><u>Notice</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Notice</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs3) > 0) {
                        for ($i = 0; $i < count($rs3); $i++) {
                            $row = $rs3[$i];
                            $index = $i + 1;
                            $rs3UserName = $row['UserName'];
                            $rs3Notice = $row['Notice'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs3UserName</td>
                            <td>$rs3Notice</td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='3'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total notices: $rs3Count</span>
            </div>
        </body>
    </html>
    ";
} else if ($_SESSION['role'] == "Railway Operator") {
    $rs1 = RailwayOperator::getRoute();
    $rs2 = RailwayOperator::getSchedule();
    $rs3 = RailwayOperator::getTrain();

    $rs1Count = RailwayOperator::getRouteCount();
    $rs2Count = RailwayOperator::getScheduleCount();
    $rs3Count = RailwayOperator::getTrainCount();

    // Generate HTML content for the report
    $html = "
    <html>
        <head>
            <style>
                table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
                }
            </style>
        </head>
        <body>
            <h1 align='center'>Statistical Report - Railway Staff</h1>
            <h4>Generated by: $username</h4>
            <h4>Generated at: $currentDateTime</h4>
            <h3><u>Route</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Route Name</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs1) > 0) {
                        for ($i = 0; $i < count($rs1); $i++) {
                            $row = $rs1[$i];
                            $index = $i + 1;
                            $rs1RouteName = $row['Route_Name'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs1RouteName</td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='2'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total routes: $rs1Count</span>
            </div>
            <h3><u>Schedule</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Route</th>
                            <th>Train Name</th>
                            <th>Start Station</th>
                            <th>End Station</th>
                            <th>Arrival Time</th>
                            <th>Depature Time</th>
                        </tr>
                    </thead>
                    <tbody>";
                    $dbcon = new DbConnector;
                    $con = $dbcon->connect();
                    if (count($rs2) > 0) {
                        for ($i = 0; $i < count($rs2); $i++) {
                            $row = $rs2[$i];
                            $query = "SELECT Route_Name FROM Route WHERE Route_Id = ?;";
                            $pstmt = $con->prepare($query);
                            $pstmt->bindValue(1, $row['Route_Id']);
                            $pstmt->execute();
                            $routeName = $pstmt->fetch(PDO::FETCH_BOTH)[0];
                            $index = $i + 1;
                            $rs2TrainName = $row['Train_Name'];
                            $rs2StartStation = $row['Start_Station_Id'];
                            $rs2EndStation = $row['End_Station_Id'];
                            $rs2ArrTime = $row['Arr_Time'];
                            $rs2DeptTime = $row['Dept_Time'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$routeName</td>
                            <td>$rs2TrainName</td>
                            <td>$rs2StartStation</td>
                            <td>$rs2EndStation</td>
                            <td>$rs2ArrTime</td>
                            <td>$rs2DeptTime</td>
                        </tr>
                    ";
                        }
                    } else {
                    $html .= "
                        <tr>
                            <td colspan='7'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total schedules: $rs2Count</span>
            </div>
            <h3><u>Train</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Train Name</th>
                            <th>Canteen</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs3) > 0) {
                        for ($i = 0; $i < count($rs3); $i++) {
                            $row = $rs3[$i];
                            $index = $i + 1;
                            $rs3TrainName = $row['Train_Name'];
                            $rs3Canteen = $row['Canteen'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs3TrainName</td>
                            <td>$rs3Canteen</td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='3'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total trains: $rs3Count</span>
            </div>
        </body>
    </html>
    ";
} else if ($_SESSION['role'] == "Cater Staff") {
    $rs1 = CaterStaff::getFoodOrders();
    $rs2 = CaterStaff::getFood();
    $rs3 = CaterStaff::getSum();

    $rs1Count = CaterStaff::getOrderCount();
    $rs2Count = CaterStaff::getFoodCount();

    // Generate HTML content for the report
    $html = "
    <html>
        <head>
            <style>
                table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
                }
            </style>
        </head>
        <body>
            <h1 align='center'>Statistical Report - Cater Staff</h1>
            <h4>Generated by: $username</h4>
            <h4>Generated at: $currentDateTime</h4>
            <h3><u>Food Orders</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>";
                    $dbcon = new DbConnector;
                    $con = $dbcon->connect();
                    if (count($rs1) > 0) {
                        for ($i = 0; $i < count($rs1); $i++) {
                            $row = $rs1[$i];
                            $query = "SELECT UserName FROM User WHERE User_Id = ?;";
                            $pstmt = $con->prepare($query);
                            $pstmt->bindValue(1, $row['User_Id']);
                            $pstmt->execute();
                            $username = $pstmt->fetch(PDO::FETCH_BOTH);
                            $index = $i + 1;
                            $rs1Email = $row['Email'];
                            $rs1Quantity = $row['Quantity'];
                            $rs1TotalPrice = $row['Total_Price'];
                            $rs1Status = $row['Status'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$$username</td>
                            <td>$rs1Email</td>
                            <td>$rs1Quantity</td>
                            <td>$rs1TotalPrice</td>
                            <td>$rs1Status</td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='6'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total food orders: $rs1Count</span>
                <br>
                <span>Total income: $rs3</span>
            </div>
            <h3><u>Food</u></h3>
            <div align='left'>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Food Name</th>
                            <th>Price</th>
                            <th>Image</th>
                        </tr>
                    </thead>
                    <tbody>";
                    if (count($rs2) > 0) {
                        for ($i = 0; $i < count($rs2); $i++) {
                            $row = $rs2[$i];
                            $index = $i + 1;
                            $rs2FoodName = $row['Food_Name'];
                            $rs2Price = $row['Price'];
                            $rs2Image = $row['Image'];
                            $html .= "
                        <tr>
                            <td>$index</td>
                            <td>$rs2FoodName</td>
                            <td>$rs2Price</td>
                            <td><img src='../assets/img/food/$rs2Image' height='100' width='100'></td>
                        </tr>
                            ";
                        }
                    } else {
                        $html .= "
                        <tr>
                            <td colspan='4'>No data found</td>
                        </tr>";
                    }
                    $html .= "
                    </tbody>
                </table>
                <br>
                <span>Total food: $rs2Count</span>
            </div>
        </body>
    </html>
    ";
}

// Initialize mPDF
$mpdf = new \Mpdf\Mpdf();

// Generate PDF from HTML
$mpdf->WriteHTML($html);

// Output the PDF as a downloadable file
$mpdf->Output('Report.pdf', \Mpdf\Output\Destination::DOWNLOAD);